### PR TITLE
returns error for 'special' file types (e.g. unix devices)

### LINKED ISSUE #166: Unix: Return error when trying to open a device file
`kibi /dev/random` should fail with an error message

[std](https://doc.rust-lang.org/std/index.html)::[os](https://doc.rust-lang.org/std/os/index.html)::[unix](https://doc.rust-lang.org/std/os/unix/index.html)::[fs](https://doc.rust-lang.org/std/os/unix/fs/index.html)::[FileTypeExt](https://doc.rust-lang.org/std/os/unix/fs/trait.FileTypeExt.html#) can be used to determine the file type.

### PR DESCRIPTION
**Pull request by ilmanzo**
allows editing only actual files, e.g. no block/char device, FIFO, directory...
~~added also new option to strip out debug info in release build~~
fix #166 
still below 1024 lines of code :)

### CODE REVIEW

File: src/editor.rs [hunk 1]
```diff
@@ -422,6 +424,10 @@ impl Editor {
     /// Try to load a file. If found, load the rows and update the render and syntax highlighting.
     /// If not found, do not return an error.
     fn load(&mut self, path: &Path) -> Result<(), Error> {
+        if !std::fs::metadata(path)?.file_type().is_file() {
```
Comment (ilai-deutel) [inline src/editor.rs:427]: I think we should also keep supporting symlinks  ([is_symlink](https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.is_symlink)) as kibi seems to be working well with them

Comment (ilmanzo) [reply src/editor.rs:427]: good point!

**Comment by ilai-deutel** [comment]
@all-contributors please add @ilmanzo for code, test
